name: package
on:
  workflow_dispatch:
    inputes:
      build_revision:
        required: true
        type: string
      deploy_distro:
        required: true
        type: string

jobs:
  package:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: setup
        run: | 
          sudo ls -al
          pwd
          bash build.sh lsphp83 8.3.13 ${{ inputs.build_revision }} ${{ inputs.build_distro }} amd64
